class LocationData {
  static const Map<String, String> countryCodeToName = {
    'SG': 'Singapore',
    'IN': 'India',
    'US': 'United States',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom',
    'FR': 'France',
    'DE': 'Germany',
    'CA': 'Canada',
    'AU': 'Australia',
    'TR': 'Turkey',
    'MA': 'Morocco',
    'EG': 'Egypt',
    'SA': 'Saudi Arabia',
    'QA': 'Qatar',
    'OM': 'Oman',
    'KW': 'Kuwait',
    'BH': 'Bahrain',
    'JO': 'Jordan',
    'LB': 'Lebanon',
  };

  static const Map<String, List<String>> countriesAndCities = {
    'Singapore': ['Singapore'],
    'India': [
      'Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 
      'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli', 'Daman & Diu', 
      'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir', 
      'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 
      'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 
      'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 
      'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'
    ],
    'United States': [
      'New York City', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 
      'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose',
      'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte',
      'Indianapolis', 'San Francisco', 'Seattle', 'Denver', 'Washington D.C.',
      'Boston', 'El Paso', 'Nashville', 'Detroit', 'Oklahoma City', 
      'Portland', 'Las Vegas', 'Memphis', 'Louisville', 'Baltimore',
      'Milwaukee', 'Albuquerque', 'Tucson', 'Fresno', 'Sacramento',
      'Kansas City', 'Mesa', 'Atlanta', 'Omaha', 'Colorado Springs',
      'Raleigh', 'Miami', 'Virginia Beach', 'Oakland', 'Minneapolis',
      'Tulsa', 'Arlington', 'New Orleans', 'Wichita', 'Bakersfield',
      'Santa Clara'
    ],
    'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'],
    'United Kingdom': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Newcastle', 'Sheffield', 'Liverpool', 'Leeds', 'Bristol', 'Edinburgh'],
    'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
    'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Dusseldorf', 'Dortmund', 'Essen', 'Leipzig'],
    'Canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'],
    'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Geelong'],
    'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Konya', 'Gaziantep', 'Sanliurfa', 'Mersin'],
    'Morocco': ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Tangier', 'Agadir', 'Meknes', 'Oujda', 'Kenitra', 'Tetouan'],
    'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'El Mahalla El Kubra', 'Tanta'],
    'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Sultanah', 'Dammam', 'Taif', 'Tabuk', 'Al Kharj', 'Buraidah'],
    'Qatar': ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Madinat ash Shamal'],
    'Oman': ['Muscat', 'Salalah', 'Seeb', 'Sohar', 'Nizwa', 'Khasab'],
    'Kuwait': ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Al Farwaniyah', 'Al Jahra'],
    'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Isa Town'],
    'Jordan': ['Amman', 'Zarqa', 'Irbid', 'Russeyba', 'Al-Quwaysimah', 'Tila al-Ali'],
    'Lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Nabatieh', 'Jounieh', 'Zahle', 'Baalbek'],
  };
}
